import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import AppShell from "./AppShell";

export const metadata: Metadata = {
  title: "DER DIE DAS",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${roboto.className} bg-black`}
      >
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
